steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "backend/.env"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/eco-waste", "."]
    dir: "backend" 
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/eco-waste"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "eco-waste",
        "--image", "gcr.io/$PROJECT_ID/eco-waste",
        "--port", "3000",       
        "--timeout", "1000s",            # Increase timeout
        "--region", "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY